{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "av-scanner.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scanner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: av-scanner-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: av-scanner-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "av-scanner.fullname" . }}-deployer
      containers:
        - name: controller
          image: {{ include "av-scanner.image" . }}
          command: ["sleep", "infinity"]
          env:
            - name: SA_NAME
              value: {{ .Values.token.serviceAccount | quote }}
            - name: SA_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: TOKEN_DURATION
              value: {{ .Values.token.duration | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: inventory
              mountPath: /etc/ansible
              readOnly: true
      volumes:
        - name: ssh-key
          secret:
            secretName: {{ include "av-scanner.sshSecretName" . }}
            defaultMode: 0400
        - name: inventory
          configMap:
            name: {{ include "av-scanner.fullname" . }}-inventory
{{- end }}
