{{- if .Values.autoDeploy.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "av-scanner.fullname" . }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scanner.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: {{ include "av-scanner.fullname" . }}-deployer
      restartPolicy: Never
      containers:
        - name: deploy
          image: {{ include "av-scanner.image" . }}
          command:
            - ansible-playbook
            - playbooks/deploy.yaml
          env:
            - name: SA_NAME
              value: {{ .Values.token.serviceAccount | quote }}
            - name: SA_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: TOKEN_DURATION
              value: {{ .Values.token.duration | quote }}
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: inventory
              mountPath: /etc/ansible
              readOnly: true
      volumes:
        - name: ssh-key
          secret:
            secretName: {{ include "av-scanner.sshSecretName" . }}
            defaultMode: 0400
        - name: inventory
          configMap:
            name: {{ include "av-scanner.fullname" . }}-inventory
{{- end }}
