{{- if .Values.preInstallCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "av-scanner.fullname" . }}-validate-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scanner.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  backoffLimit: {{ .Values.preInstallCheck.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.preInstallCheck.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.preInstallCheck.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: validate-ssh
          image: {{ include "av-scanner.image" . }}
          command:
            - sh
            - -c
            - |
              echo "$INVENTORY" > /tmp/inventory.yaml
              ansible all -m ping -i /tmp/inventory.yaml
          env:
            - name: INVENTORY
              value: {{ .Values.inventory | quote }}
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: ssh-key
          secret:
            secretName: {{ include "av-scanner.sshSecretName" . }}
            defaultMode: 0400
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
