apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.token.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scanner.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "av-scanner.fullname" . }}-deployer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scanner.labels" . | nindent 4 }}
